Repository lava-nc/lava-optimization, pull requests merged in 2022-10, with the labels that each got.

#71 Add MISProblem class to support Maximum Independent Set problems.
  src/lava/lib/optimization/solvers/generic/builder.py
  src/lava/lib/optimization/utils/generators/__init__.py
  src/lava/lib/optimization/utils/generators/mis.py
  tests/lava/lib/optimization/utils/__init__.py
  tests/lava/lib/optimization/utils/generators/__init__.py
  tests/lava/lib/optimization/utils/generators/test_mis.py
Labels: enhancement

#105 Adding support for new PIPG-based QP solver in Lava
  src/lava/lib/optimization/solvers/qp/models.py
  src/lava/lib/optimization/solvers/qp/processes.py
  src/lava/lib/optimization/solvers/qp/solver.py
  tests/lava/lib/optimization/solvers/qp/test_models.py
  tests/lava/lib/optimization/solvers/qp/test_process.py
  tutorials/tutorial_01_solving_lasso.ipynb
Labels: enhancement

#61 Update OptiizationSolver with new profiler API to enable execution time measurement on Loihi2
  src/lava/lib/optimization/problems/problems.py
  src/lava/lib/optimization/solvers/generic/solver.py
  tests/lava/lib/optimization/problems/test_problems.py
  tests/lava/lib/optimization/solvers/generic/test_solver_cpu_backend.py
Labels: enhancement

#120 Fix bug in "time_to_solution" of OptimizationSolver report
  src/lava/lib/optimization/solvers/generic/solver.py
Labels: bug

#119 Update docstrings
  src/lava/lib/optimization/solvers/bayesian/models.py
  src/lava/lib/optimization/solvers/bayesian/processes.py
  src/lava/lib/optimization/solvers/bayesian/solver.py
  src/lava/lib/optimization/solvers/generic/builder.py
  src/lava/lib/optimization/solvers/generic/hierarchical_processes.py
  src/lava/lib/optimization/solvers/generic/solver.py
Labels: documentation
